name: Hexo Blog Delopy

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node modules
        # 设置包缓存目录，避免每次下载
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Hexo
        run: |
          npm install -g hexo-cli
          npm install

      - name: Deploy Hexo
        run: |
          hexo clean
          hexo generate
          hexo deploy



        #  cd ./public && git init && git add .
        #  git config user.name "w5l6j9"
        #  git config user.email "381414439@qq.com"
        #  git add .
        #  git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        #  git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:gh-pages

