name: Hexo Blog Delopy

on:
  push:
    branches:
      - source

env:
  GIT_USER: w5l6j9
  GIT_EMAIL: 381414439@qq.com
  DEPLOY_REPO: w5l6j9/w5l6j9.github.io
  DEPLOY_BRANCH: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Configuration environment
        env:
          HEXO_DEPLOY_SECRET: ${{secrets.HEXO_DEPLOY_SECRET}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"

          # 配置私钥，否则无法访问部署库，提示 git@github.com: Permission denied (publickey).
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_SECRET" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # 设置用户名和邮箱，否则提示 Please tell me who you are.
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Setup Hexo
        run: |
          npm install -g hexo-cli
          npm install

      - name: Deploy Hexo
        run: |
          hexo clean
          hexo generate
          hexo deploy


