name: Hexo Blog Delopy

on:
  push:
    branches:
      - source


env: # 统一设置环境变量
  GIT_USER: w5l6j9
  GIT_EMAIL: 381414439@qq.com
  THEME_REPO: git/next # 你使用的主题仓库地址
  THEME_BRANCH: master
  DEPLOY_REPO: git/w5l6j9.github.io # 你用来发布github pages的仓库地址
  DEPLOY_BRANCH: master
  GITHUB_TOKEN: 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

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node modules
          # 设置包缓存目录，避免每次下载
          uses: actions/cache@v1
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Hexo
        run: |
          npm install -g hexo-cli
          npm install

      - name: Deploy Hexo
        run: |
          hexo clean
          hexo generate

      - name: Deploy hexo blog
          env:
            # Github 仓库
            GITHUB_REPO: github.com/w5l6j9/w5l6j9.github.io
          # 将编译后的博客文件推送到指定仓库
          run: |
            cd ./public && git init && git add .
            git config user.name "w5l6j9"
            git config user.email "381414439@qq.com"
            git add .
            git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
            git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:master

