name: Hexo Blog Delopy

on:
  push:
    branches:
      - source


env: # 统一设置环境变量
  GIT_USER: w5l6j9
  GIT_EMAIL: 381414439@qq.com
  THEME_REPO: git/next # 你使用的主题仓库地址
  THEME_BRANCH: master
  DEPLOY_REPO: git/w5l6j9.github.io # 你用来发布github pages的仓库地址
  DEPLOY_BRANCH: master
  GITHUB_TOKEN: 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

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup Hexo
        run: |
          npm install -g hexo-cli
          npm install

      - name: Deploy Hexo
        run: |
          hexo clean
          hexo generate
          hexo deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ env.GITHUB_TOKEN }}
          # 部署到 master 分支
          target_branch: master
          external_repository: ${{ env.DEPLOY_REPO }} # Hexo.git 的仓库地址
          publish_branch: ${{ env.DEPLOY_BRANCH }}
          publish_dir: ./public # 使用Hexo/hugo等生成静态页面的目录
          user_name: ${{ env.GIT_USER }}
          user_email: ${{ env.GIT_EMAIL }}
          #GH_PAT: ${{ secrets.GH_PAT }}
